### ISSUE TITLE
Issues when running the notebook on Colab

### ISSUE THREAD

**Issue by theimgclist** [lexfridman/mit-deep-learning#11]
Hi. I tried to run DeepLearningBasics notebook on Colab.  
Below are some of the issues I came across:

The code to download mnist_dream.mp4 video when using Colab doesn't work if ran as is:  

```
mnist_dream_path = urllib.request.urlretrieve(os.path.join(deep_repo_url, 'mit_driveseg_sample.mp4')[0]
```   
   
deep_repo_url is not declared anywhere and the video mentioned in the code is incorrect   
 
I tried below two versions of code to download the video and both worked:    

```
 !wget https://github.com/lexfridman/mit-deep-learning/tree/master/tutorial_deep_learning_basics/images/mnist_dream.mp4
```  

```
import urllib
urllib.request.urlretrieve("https://github.com/lexfridman/mit-deep-learning/tree/master/tutorial_deep_learning_basics/images/mnist_dream.mp4","mnist_dream.mp4")
```  

The code `ret, img = cap.read()` returns the tuple False, None. There seems to be some problem with VideoCapture() on Colab.    

Since the img is not being returned as expected, the rest of the code to do inference on mnist_dream.mp4 frames isn't working.  

I remember facing problems in the past when using OpenCV methods on Colab. I'm not aware of any fix or workaround for this issue atm.  

Besides these issues on Colab, below are few things that can be modified:  

The function`def plot_history(history)` works just fine without the parameter *history* since it's not being used anywhere inside the function  

In the below code, rmse needs to be printed instead of rmse_final

```
test_features_norm = (test_features - train_mean) / train_std
mse, _, _ = model.evaluate(test_features_norm, test_labels)
rmse = np.sqrt(mse)
print('Root Mean Square Error on test set: {}'.format(round(rmse_final, 3)))
```

**Comment by lexfridman** [comment]
Fixed all. Great finds and suggestions!
