### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by zhyongquan** [lexfridman/mit-deep-learning#6]
can i translate this repo to Chinese?

**Comment by MahmoudAbdelRahman** [comment]
I can translate it to Arabic as well!

**Comment by PauloPaixao** [comment]
can I translate it to Portuguese!?

**Comment by heyaudace** [comment]
Can I translate to Kinyarwanda as well?

**Comment by lexfridman** [comment]
Hi all, we'll consider translations once the repository matures and more tutorials are added. Thanks all for the kind offers.
